### PR TITLE
Implement `ConditionallySelectable` for `[T; N]`

### LINKED ISSUE #82: Implement `ConditionallySelectable` for `[T; N]`?
This kind of implementation seems fairly natural for big-int libraries (for example [curve25519-dalek](https://github.com/dalek-cryptography/curve25519-dalek/blob/b307c155c966c16b81f63a5872a1ec1977829ddf/src/backend/serial/u64/field.rs#L220) essentially does this for the specific type `[u64; 5]`). Now that min-const-generics are stabilized, it would nice to have a general implementation of this.

I am imagining a straightforward generalization of the curve25519-dalek technique:

    impl<const N: usize> ConditionallySelectable for [T; N] where T : Copy + Default {
    fn conditional_select(
        a: &[T; N],
        b: &[T; N],
        choice: Choice,
    ) -> [T; N] {
        let mut output = [T::default(); N];
        for i in 0..N {
            output[i] = T::conditionally_selectable(&a[i], &b[i], choice);
        }
        output
    }

I don't know if the trait bound I give for `T` is precisely what is required though. It's not fully clear to me currently why `ConditionallySelectable` requires `T` to be `Copy`.

For my particular use case, I have a simple wrapper type around a `[u64; N]` that is not Copy (I want to write some constant-time bigint arithmetic that minimizes stack allocations. As a theorist who is trying to learn Rust I have no clue how actually useful this is, but it is the project I chose). If the above was implemented for `[T; N]`, I could implement `ConditionallySelectable`. It could also potentially replace the code in curve25519-dalek, but as you probably want the loop unrolled that might not be worth it (although hopefully the compiler would unroll it of course).

### PR DESCRIPTION
**Pull request by survived**
PR makes arrays of any size "conditionally selectable" as long as `T` is conditionally selectable. Changes MSRV to 1.51.

Closes #82

### CODE REVIEW

**Comment by fjarri** [comment]
So, what's stopping this from being merged? I would very much like to use this functionality.

**Comment by tarcieri** [comment]
@fjarri the only people with commit access are currently on sabbatical. We can discuss getting access with them.

**Review by isislovecruft — COMMENTED** [review]
Hi @survived! Thanks so much for the patch. It LGTM. The only minor qualm I have is the MSRV bump.. perhaps there's some way to feature gate this and then display a warning if someone doesn't have a new enough rustc version? (I know, I know, 1.51 is old, but the latest stable Debian for example is still shipping 1.41 and _a lot_ of prod systems are running with that.)

**Comment by survived** [comment]
Hi @isislovecruft, I've added `const-generics` feature that adds arrays support when enabled (it's disabled by default). I also updated readme to mention this feature and travis.yml to test it (tho I don't see that CI is running).

**Review by isislovecruft — APPROVED** [review]
Thanks so much @survived! LGTM. Merging for 2.5.0.

**Pull request merged**
