### PR TITLE
Add i128 feature, test MSRV and no_std

### PR DESCRIPTION
**Pull request by newpavlov**
Fixes: #28 

Regarding replaced `match`, proposed code produces the same [assembly](https://rust.godbolt.org/z/G5tR6o) and does not use `hint::unreachable_unchecked()` which was stabilized only in Rust 1.27. (plus it's minus one line of unsafe code)

### CODE REVIEW

**Comment by newpavlov** [comment]
Also I took a bit of liberty and have simplified CI config a little.

**Comment by newpavlov** [comment]
@hdevalence @isislovecruft 
Any news on this?

**Comment by hdevalence** [comment]
Oops, I got distracted by other stuff, thanks for the reminder!

**Comment by newpavlov** [comment]
Do you have an ETA for publishing? I think this PR is backwards compatible, so it can be done with just patch version bump.

**Comment by kpcyrd** [comment]
For context, a new release would unblock https://github.com/RustCrypto/traits/pull/22 which currently both fedora and debian are waiting on. :) Thanks for your work!

**Comment by newpavlov** [comment]
You mean `1.0.0-pre0` version will be published? IIUC we will not be able to use [semver trick](https://github.com/dtolnay/semver-trick) on it, and because `subtle` will be a part of public API for `Mac` trait we will have to publish a minor version update. So I think the following strategy will be more optimal:
- publish `v0.9.1` with this PR
- optionally publish `v1.0.0-pre0` which will have the same code as `v0.9.1`
- when you decide to publish `v1.0.0` and if it will be backwards compatible with `v0.9`, publish `v0.9.2` with semver trick, so `subtle` version in dependent crates can be bumped to `v1.0` in a backwards compatible way.

**Comment by hdevalence** [comment]
We published a `1.0.0` version, and we're intending to maintain stability of that API going forwards. It seems better to migrate to the stable API now, rather than trying to keep backwards compatibility. Over time we would actually like to yank the pre-release versions of `subtle`, but we don't have any plans to do that immediately.

**Comment by newpavlov** [comment]
Well, this works too. :)

**Comment by hdevalence** [comment]
No worries, sorry to do the version bump now, it just seemed like we were basically there and hadn't gotten around to doing it yet, whereas maintaining multiple versions would cause more work later.

**Pull request merged**
